In [1]:
import pandas as pd
import numpy as np

In [8]:
forex_data = pd.read_csv("Technical_Data/forex_with_indicators.csv")

forex_data.head()

,DateTime,PairID,PairName,Open,High,Low,Close,Volume,Spread,SMA_10,SMA_20,EMA_10,RSI,MACD,Signal_Line,Middle_Band,Upper_Band,Lower_Band
0,2023-01-01 00:00:00,1,EUR/USD,1.08103,1.08103,1.08019,1.08054,2651,0.9,NaN,NaN,1.080540,NaN,0.000000,0.000000,NaN,NaN,NaN
1,2023-01-01 01:00:00,1,EUR/USD,1.08010,1.08043,1.07974,1.08028,2292,1.0,NaN,NaN,1.080493,NaN,-0.000021,-0.000004,NaN,NaN,NaN
2,2023-01-01 02:00:00,1,EUR/USD,1.08036,1.08158,1.07961,1.08054,1796,1.2,NaN,NaN,1.080501,NaN,-0.000016,-0.000007,NaN,NaN,NaN
3,2023-01-01 03:00:00,1,EUR/USD,1.08068,1.08126,1.07973,1.08088,4019,1.4,NaN,NaN,1.080570,NaN,0.000015,-0.000002,NaN,NaN,NaN
4,2023-01-01 04:00:00,1,EUR/USD,1.08042,1.08042,1.07967,1.08030,2207,1.6,NaN,NaN,1.080521,NaN,-0.000007,-0.000003,NaN,NaN,NaN

In [9]:
print(forex_data.shape)

print(forex_data.columns)

(500, 18)
Index(['DateTime', 'PairID', 'PairName', 'Open', 'High', 'Low', 'Close',
       'Volume', 'Spread', 'SMA_10', 'SMA_20', 'EMA_10', 'RSI', 'MACD',
       'Signal_Line', 'Middle_Band', 'Upper_Band', 'Lower_Band'],
      dtype='str')

In [11]:
import os
print(os.listdir())

['01_Data_Loading.ipynb', '02_Data_Cleaning.ipynb', '03_EDA.ipynb', '04_Technical_Indicators.ipynb', '05_Signal_Generation.ipynb', '06_Machine_Learning.ipynb', '07_Reinforcement_Learning.ipynb', '08_Model_Evaluation.ipynb', '09_PowerBI_Data_Preparation.ipynb', '10_Final_AI_Agent.ipynb', 'Cleaned_Data', 'Data', 'EDA_Outputs', 'Machine_learning_output', 'Model_Evaluation_Output', 'Power BI', 'Python', 'Reinforcement_Learning', 'Signal_data', 'signal_outputs', 'Technical_Data']

In [13]:
print(os.listdir("signal_outputs"))

[]

In [17]:
import os

for folder in os.listdir():
    if os.path.isdir(folder):
        print(folder)

Cleaned_Data
Data
EDA_Outputs
Machine_learning_output
Model_Evaluation_Output
Power BI
Python
Reinforcement_Learning
Signal_data
Technical_Data

In [19]:
import os

os.makedirs("signal_outputs", exist_ok=True)

forex_data.to_csv(
    "signal_outputs/forex_signals.csv",
    index=False
)

In [20]:
import os
print(os.listdir("signal_outputs"))

['forex_signals.csv']

In [22]:
import pandas as pd

forex_data = pd.read_csv("Signal_Data/forex_with_signals.csv")

forex_data.head()

,DateTime,PairID,PairName,Open,High,Low,Close,Volume,Spread,SMA_10,SMA_20,EMA_10,RSI,MACD,Signal_Line,Middle_Band,Upper_Band,Lower_Band,Signal
0,2023-01-01 00:00:00,1,EUR/USD,1.08103,1.08103,1.08019,1.08054,2651,0.9,NaN,NaN,1.080540,NaN,0.000000,0.000000,NaN,NaN,NaN,HOLD
1,2023-01-01 01:00:00,1,EUR/USD,1.08010,1.08043,1.07974,1.08028,2292,1.0,NaN,NaN,1.080493,NaN,-0.000021,-0.000004,NaN,NaN,NaN,HOLD
2,2023-01-01 02:00:00,1,EUR/USD,1.08036,1.08158,1.07961,1.08054,1796,1.2,NaN,NaN,1.080501,NaN,-0.000016,-0.000007,NaN,NaN,NaN,HOLD
3,2023-01-01 03:00:00,1,EUR/USD,1.08068,1.08126,1.07973,1.08088,4019,1.4,NaN,NaN,1.080570,NaN,0.000015,-0.000002,NaN,NaN,NaN,HOLD
4,2023-01-01 04:00:00,1,EUR/USD,1.08042,1.08042,1.07967,1.08030,2207,1.6,NaN,NaN,1.080521,NaN,-0.000007,-0.000003,NaN,NaN,NaN,HOLD

In [23]:
powerbi_data = forex_data[[
    "DateTime",
    "Open",
    "High",
    "Low",
    "Close",
    "Volume",
    "SMA_10",
    "SMA_20",
    "EMA_10",
    "RSI",
    "MACD",
    "Signal_Line",
    "Upper_Band",
    "Lower_Band",
    "Signal"
]]

In [24]:
powerbi_data.head()

,DateTime,Open,High,Low,Close,Volume,SMA_10,SMA_20,EMA_10,RSI,MACD,Signal_Line,Upper_Band,Lower_Band,Signal
0,2023-01-01 00:00:00,1.08103,1.08103,1.08019,1.08054,2651,NaN,NaN,1.080540,NaN,0.000000,0.000000,NaN,NaN,HOLD
1,2023-01-01 01:00:00,1.08010,1.08043,1.07974,1.08028,2292,NaN,NaN,1.080493,NaN,-0.000021,-0.000004,NaN,NaN,HOLD
2,2023-01-01 02:00:00,1.08036,1.08158,1.07961,1.08054,1796,NaN,NaN,1.080501,NaN,-0.000016,-0.000007,NaN,NaN,HOLD
3,2023-01-01 03:00:00,1.08068,1.08126,1.07973,1.08088,4019,NaN,NaN,1.080570,NaN,0.000015,-0.000002,NaN,NaN,HOLD
4,2023-01-01 04:00:00,1.08042,1.08042,1.07967,1.08030,2207,NaN,NaN,1.080521,NaN,-0.000007,-0.000003,NaN,NaN,HOLD

In [25]:
print(powerbi_data.isnull().sum())

DateTime        0
Open            0
High            0
Low             0
Close           0
Volume          0
SMA_10          9
SMA_20         19
EMA_10          0
RSI            13
MACD            0
Signal_Line     0
Upper_Band     19
Lower_Band     19
Signal          0
dtype: int64

In [26]:
print(powerbi_data.dtypes)

DateTime           str
Open           float64
High           float64
Low            float64
Close          float64
Volume           int64
SMA_10         float64
SMA_20         float64
EMA_10         float64
RSI            float64
MACD           float64
Signal_Line    float64
Upper_Band     float64
Lower_Band     float64
Signal             str
dtype: object

In [27]:
import os

os.makedirs("PowerBI_Output", exist_ok=True)

In [28]:
powerbi_data.to_csv(
    "PowerBI_Output/powerbi_dataset.csv",
    index=False
)

In [29]:
import os

print(os.listdir("PowerBI_Output"))

['powerbi_dataset.csv']

In [30]:
['powerbi_dataset.csv']

['powerbi_dataset.csv']

In [31]:
import pandas as pd

forex_data = pd.read_csv("Signal_Data/forex_with_signals.csv")

forex_data.head()

,DateTime,PairID,PairName,Open,High,Low,Close,Volume,Spread,SMA_10,SMA_20,EMA_10,RSI,MACD,Signal_Line,Middle_Band,Upper_Band,Lower_Band,Signal
0,2023-01-01 00:00:00,1,EUR/USD,1.08103,1.08103,1.08019,1.08054,2651,0.9,NaN,NaN,1.080540,NaN,0.000000,0.000000,NaN,NaN,NaN,HOLD
1,2023-01-01 01:00:00,1,EUR/USD,1.08010,1.08043,1.07974,1.08028,2292,1.0,NaN,NaN,1.080493,NaN,-0.000021,-0.000004,NaN,NaN,NaN,HOLD
2,2023-01-01 02:00:00,1,EUR/USD,1.08036,1.08158,1.07961,1.08054,1796,1.2,NaN,NaN,1.080501,NaN,-0.000016,-0.000007,NaN,NaN,NaN,HOLD
3,2023-01-01 03:00:00,1,EUR/USD,1.08068,1.08126,1.07973,1.08088,4019,1.4,NaN,NaN,1.080570,NaN,0.000015,-0.000002,NaN,NaN,NaN,HOLD
4,2023-01-01 04:00:00,1,EUR/USD,1.08042,1.08042,1.07967,1.08030,2207,1.6,NaN,NaN,1.080521,NaN,-0.000007,-0.000003,NaN,NaN,NaN,HOLD